jest.mock('./index.js', () => ({
  analyticsEventEnabled: jest.fn(),
  componentDidAppearListener:jest.fn(),
  crashNow: jest.fn(),
  currentSessionId: jest.fn(),
  endInteraction:jest.fn(),
  getReactNativeVersion:jest.fn(),
  httpResponseBodyCaptureEnabled: jest.fn(),
  incrementAttribute: jest.fn(),
  isAgentStarted: jest.fn(),
  LogLevel: {
    AUDIT: 'AUDIT',
    ERROR: 'ERROR',
    INFO: 'INFO',
    VERBOSE: 'VERBOSE',
    WARNING: 'WARNING'
  },
  networkErrorRequestEnabled: jest.fn(),
  networkRequestEnabled: jest.fn(),
  noticeHttpTransaction: jest.fn(),
  noticeNetworkFailure: jest.fn(),
  onNavigationStateChange: jest.fn(),
  onStateChange:jest.fn(),
  recordBreadcrumb: jest.fn(),
  recordCustomEvent: jest.fn(),
  recordError: jest.fn(),
  recordMetric: jest.fn(),
  removeAllAttributes: jest.fn(),
  removeAttribute: jest.fn(),
  sendConsole: jest.fn(),
  setAttribute: jest.fn(),
  setInteractionName:jest.fn(),
  setJSAppVersion: jest.fn(),
  setMaxEventBufferTime: jest.fn(),
  setMaxEventPoolSize: jest.fn(),
  setUserId: jest.fn(),
  shutdown: jest.fn(),
  startAgent: jest.fn(),
  recordReplay: jest.fn(),
  pauseReplay: jest.fn(),
  addHTTPHeadersTrackingFor: jest.fn(),
  startInteraction: jest.fn()
}));
