name: Change Tracking Marker
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      confirmation:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Are you sure you want to release?'
        type: boolean
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: "${{ env.RELEASE_VERSION }}"
          user: "${{ github.actor }}"
